# -*- coding: utf-8 -*-
"""devops new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BnMyyFSZeUIYo60D3tJI0MfL20yLTM5k
"""

Animals = ['cat','dog','turtle']

for x in Animals:
  print(Animals)